# Generated by Django 4.0.1 on 2022-01-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('searth', models.CharField(max_length=40)),
                ('online', models.IntegerField()),
            ],
        ),
    ]
