# Generated by Django 4.0.1 on 2022-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Russia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField()),
                ('main', models.CharField(max_length=20)),
            ],
        ),
    ]
